### ISSUE TITLE
API answers with 400 bad Request

### ISSUE THREAD

**Issue by seisfeld** [dhogborg/atnetgo#2]
Hi,

as of yesterday i get the following for every request i send. I did not change my username/password nor the application id and secret:

```
$ atnetgo 
ERRO[0000] client error                                  error=oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant"} 
```

After several tries this results in account suspension for 10 minutes.

cheers
Stephan

**Comment by dhogborg** [comment]
Unclear why this is happening to you (edit: likely solution below). Cannot reproduce with current release build (works as expected).

Edit: You need to specify username and password to fetch the content of your account. You can do that with either switches (below) or environment variables.

`atnetgo -u <username> -p <password> pretty`

**Comment by seisfeld** [comment]
Yap i'm using the environment variables. I did not check the last few days. I rechecked now and it worked again (with no changes). Maybe it was an API glitch or whatever. I will keep an eye on it. Thanks for checking though and sorry for the trouble. :)

cheers
Stephan
