### ISSUE TITLE
Issue with wind gauge

### ISSUE THREAD

**Issue by StrikeZW** [dhogborg/atnetgo#3]
it seems that atnetgo is unable handle user values from the module wind gauge

will there be a fix for that?

**Comment by dhogborg** [comment]
I would very much like to add functionality for the anemometer. Unfortunately I don't have a wind gauge so I cant validate the function of the app. Do you have a station that you can allow me to access though a guest account while debugging?

**Comment by StrikeZW** [comment]
Sure,
I would like to give support

https://www.netatmo.com/invitation/station/aBE9CW18Oyrea28/70:ee:50:01:ed:f8

Stations name = Mont Chanson

Kind regards
Stefan

Von meinem iPhone gesendet

**Comment by dhogborg** [comment]
Thank you!
Thanks to your station I've identified the problem and fixed it. I will hopefully find time to prepare a fix shortly.

**Comment by dhogborg** [comment]
A new release is published, this fixes the issues with the wind gauge. 
https://github.com/dhogborg/atnetgo/releases/tag/v0.0.4
